name: Send Discord Message Daily

on:
  schedule:
    - cron: '0 7 * * *'  # → 9h heure française (UTC+2 en été)
  workflow_dispatch:      # Permet de lancer manuellement aussi

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: python send_once.py
